LeoWallenstal/NGO-Projekt

- .gitignore
Tror inte .xml och .mf behöver åka med varje gång
> Uppdaterade .gitignore 

- src/ngo2024/Anvandare.java
- src/ngo2024/Inloggning.java
- src/ngo2024/Meny.form
- src/ngo2024/Meny.java
Ny klass för användare. Modifierat meny och inloggning för att hantera användarklassen
> Ny klass för användare.

- src/ngo2024/Anvandare.java
- src/ngo2024/Inloggning.java
Ändrade så man hämtar uppgifter edfter aid
> Små ändringar i konstruktorn för användare.

- src/ngo2024/Validerare.java
utökade valideringsklassen med några fler funktioner
> utökat valideringsklassen med några funktioner

- src/ngo2024/Anvandare.java
Jag har ändrat så att en användares uppgifter nu sparas i en HashMap. Nyckeln är namnet på kolumnen för en anstallds attribut.
> Hash map anvandare uppgifter

- src/ngo2024/Meny.java
> fixat navigering till projektvy

- src/ngo2024/MinaUppgifter.java
- src/ngo2024/MinaUppgifterRedigera.java
Adderade metoder till MinaUppgifter som sätter storleken på fönstret till 75% av användarens skärmstorlek. Flyttade även alla label setters från konstruktorn till en metod
> UppgifterMetoder

- src/ngo2024/AndraLosenord.form
- src/ngo2024/AndraLosenord.java
Fixat kontroller vid ändring av lösenord. Innehåller ännu ingen validering.
I rad194 ska det läggas in db ändringar.
> AndraLosenord feature

- .gitignore
- src/ngo2024/Projekt.form
- src/ngo2024/Projekt.java
Skapat och namngett kolumner, inte fått datahanteringen att fungera än.
> --update projekt

- src/ngo2024/Anvandare.java
- src/ngo2024/Meny.form
- src/ngo2024/Meny.java
Kontroll på anvandare om den är admin och/eller handläggare.
> BehorighetPaAnvandare

- src/ngo2024/Projekt.form
- src/ngo2024/Projekt.java
Nu står kolumnerna i rätt ordning, och rätt data på rätt plats.
> Fortsatt lite på projekt

- src/ngo2024/Projekt.form
- src/ngo2024/Projekt.java
Kan nu också visa den inloggade användarens avdelnings projekt. Inte dubbelkollat det faktiska resultatet, men det ser rimligt ut
> projektForts2

- src/ngo2024/Inloggning.form
- src/ngo2024/Inloggning.java
Adderade login knappar för att testa admin/handläggare/anställd
> loginButtons

- src/ngo2024/Meny.form
- src/ngo2024/Meny.java
> 'Logga ut'-knapp

- nbproject/project.properties
Reverts LeoWallenstal/NGO-Projekt#36
> Revert "addedJDatePickerLib"

- src/ngo2024/Projekt.java
- src/ngo2024/fonster/LaggTillProjektFonster.java
Nu funkar det att inserta ett projekt i databastabellen 'projekt', som även insertar ev. partners IDn i sambandstabellen 'projekt_partner'
> Projekt - Insert i DB

- src/ngo2024/fonster/ProjektFonster.form
- src/ngo2024/fonster/ProjektFonster.java
- src/ngo2024/fonster/ProjektInfoFonster.form
- src/ngo2024/fonster/ProjektInfoFonster.java
ändrat muspekaren när den hovrar över celler i kolumnerna projektnamn och projektchef
> ändrat muspekaren

- src/ngo2024/Projekt.java
- src/ngo2024/ProjektRegister.java
- src/ngo2024/fonster/ProjektFonster.form
- src/ngo2024/fonster/ProjektFonster.java
> Projekt - Datumsortering

- src/ngo2024/fonster/LaggTillProjektFonster.form
- src/ngo2024/fonster/LaggTillProjektFonster.java
- src/ngo2024/fonster/ProjektFonster.java
Listan uppdateras automatiskt när man lägger till/tar bort
kan i nuläget inte ta bort partner
> Projekt och Partner

- src/ngo2024/Avdelning.java
- src/ngo2024/fonster/AvdelningFonster.form
- src/ngo2024/fonster/AvdelningFonster.java
- src/ngo2024/fonster/ProjektFonster.form
- src/ngo2024/fonster/ProjektFonster.java
- Söka på epost nu också
- Små estetiska ändringar, med lite feedback text i sökfältsrutan som ändras med kategorin, i AvdelningsFonster och samma i ProjektFonster
> Avdelning - Fixat epostsök

- src/ngo2024/Partner.java
- src/ngo2024/fonster/PartnerFonster.form
- src/ngo2024/fonster/PartnerFonster.java
- src/ngo2024/fonster/PartnerInfoFonster.form
- src/ngo2024/fonster/PartnerInfoFonster.java
- src/ngo2024/fonster/ProjektFonster.form
- src/ngo2024/fonster/ProjektFonster.java
- src/ngo2024/fonster/VarningJaNejFonster.form
- src/ngo2024/fonster/VarningJaNejFonster.java
- Nu kan man ta bort en partner, listan uppdateras automatiskt, tas bort från databasen ok, osv.
- 'Ja/Nej' prompten har en fungerande storlek (har testa de flesta olika partners/anställda med långa namn) men inte perfekt. Man skulle ju vilja ha någon sorts relativ storlek till hur stor varningUndertextLbl är (+ lite padding).
> Update partner - ta bort, mm

- src/ngo2024/Partner.java
- src/ngo2024/PartnerRegister.java
- src/ngo2024/Projekt.java
- src/ngo2024/fonster/LaggTillProjektFonster.java
- src/ngo2024/fonster/ProjektInfoFonster.java
- src/ngo2024/fonster/RedigeraProjektFonster.form
- src/ngo2024/fonster/RedigeraProjektFonster.java
> projekt redigera

- src/ngo2024/Avdelning.java
- src/ngo2024/PartnerRegister.java
- src/ngo2024/ProjektRegister.java
- src/ngo2024/Stad.java
Lite remove, equals och contains funktioner i registerklasserna
> Hjälpfunktioner

- src/ngo2024/fonster/ProjektInfoFonster.java
- src/ngo2024/fonster/RedigeraProjektFonster.form
- src/ngo2024/fonster/RedigeraProjektFonster.java
- Fortsatt redigering på projekt, snart är allt på plats för att börja validera och sen SQL UPDATE in i databasen.
> Projektredigering Forts

- src/ngo2024/Anvandare.java
- src/ngo2024/Avdelning.java
- src/ngo2024/AvdelningsRegister.java
- src/ngo2024/fonster/AvdelningFonster.java
- src/ngo2024/fonster/RedigeraAvdelningFonster.form
- src/ngo2024/fonster/RedigeraAvdelningFonster.java
Jag har fått ner tiden det tog på min laptop med ca 67%. Hittade flera sätt man kan göra för att minska tiden ännu mer som tex att man kommer in i det nya fönstret även om allting inte har hämtats klart och att det då vissas nån typ av loading ikon men det innefattade en hel del mer avancerade metoder så känns inte som nått att ge sig på.
Finns för tillfället dubbla konstruktorer för Avdelning och Anvandare främst för jag inte vill ändra i allt för många filer.
> Delay tweaks

- src/ngo2024/Projekt.java
- src/ngo2024/fonster/LaggTillProjektFonster.java
- src/ngo2024/fonster/OsparadeAndringarFonster.java
- src/ngo2024/fonster/ProjektFonster.java
- src/ngo2024/fonster/ProjektInfoFonster.form
- src/ngo2024/fonster/ProjektInfoFonster.java
- src/ngo2024/fonster/RedigeraProjektFonster.form
- src/ngo2024/fonster/RedigeraProjektFonster.java
- Typ en draft på projektredigering! 99.9%
> Projektredigering

- src/ngo2024/fonster/RedigeraProjektFonster.java
> fix redigeraProjekt

- src/ngo2024/Anvandare.java
- src/ngo2024/Avdelning.java
- src/ngo2024/Land.java
- src/ngo2024/Partner.java
- src/ngo2024/PartnerRegister.java
- src/ngo2024/Projekt.java
- src/ngo2024/ProjektRegister.java
- src/ngo2024/Stad.java
- src/ngo2024/StadRegister.java
- src/ngo2024/fonster/LaggTillPartnerFonster.java
- src/ngo2024/fonster/LaggTillProjektFonster.java
- src/ngo2024/fonster/RedigeraPartnerInfoFonster.java
Reverts LeoWallenstal/NGO-Projekt#94
> Revert "Update stad.java"

- src/ngo2024/fonster/LaggTillProjektFonster.form
- src/ngo2024/fonster/LaggTillProjektFonster.java
Lägga till handläggare på projekt
> Lägga till handläggare på projekt

- src/ngo2024/fonster/RedigeraProjektFonster.java
Fixade en bug där projektchefen inte visas korrekt i redigeringsläget.
> liten bugfix RedigeraProjekt

- src/ngo2024/fonster/AvdelningFonster.java
- src/ngo2024/fonster/MinaUppgifterFonster.java
> AnstalldInfoFonster

- src/ngo2024/ProjektRegister.java
- src/ngo2024/fonster/ProjektFonster.java
Nu ska filtreringen funka bättre, förhoppningsvis.... kanske. Inte optimalt gjort tror jag, men mer funktionellt.
> bugfix Projektvy

- src/ngo2024/Partner.java
- src/ngo2024/fonster/RedigeraPartnerInfoFonster.form
- src/ngo2024/fonster/RedigeraPartnerInfoFonster.java
> fixPartnerID

- src/ngo2024/AnvandarRegister.java
- src/ngo2024/Anvandare.java
- src/ngo2024/Avdelning.java
- src/ngo2024/AvdelningsRegister.java
- src/ngo2024/Land.java
- src/ngo2024/LandRegister.java
- src/ngo2024/NGO2024.java
- src/ngo2024/Partner.java
- src/ngo2024/PartnerRegister.java
- src/ngo2024/Projekt.java
- src/ngo2024/ProjektRegister.java
- src/ngo2024/Projektstatus.java
- src/ngo2024/SokKategori.java
- src/ngo2024/Stad.java
- src/ngo2024/StadRegister.java
- Lagt till kommentarer i alla .java filer i ngo2024 foldern.
kanske också en katt
> Kommentarer
